= TerraNet BSP

To get the BSP you need to have `repo` installed and use it as:

Install the `repo` utility:

[source,console]
$: mkdir ~/bin
$: curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$: chmod a+x ~/bin/repo

Download the BSP source:

[source,console]
$: PATH=${PATH}:~/bin
$: mkdir terranet
$: cd terranet
$: repo init -u https://github.com/HaoWu555/terranet.git -b master
$: repo sync

At the end of the commands you have every metadata you need to start work with.

Download the TerraNet source:
1. download the TerraNet layer: meta-terranet and put it in the file sources
2. cd sources
3. mkdir terranet-support
4. download the TerraNet kernel: linux-imx (master branch) in the sources/terranet-support
5. download the rtlwifi-next in the sources/terranet-support

Before bitbake, you need to source your enviroment to use python2.7 by "source venv/bin/activate" 

To start a simple image build:

[source,console]
$: source ./setup-environment build
$: bitbake core-image-minimal

You can use any directory to host your build.

Add the meta-terranet layer into build/conf/bblayer.com

Add "require conf/terranet.conf" in the build/conf/local.conf




